id: I95652657
ocr_import_info:
  timestamp: '2023-09-26T14:22:34.765184+00:00'
  batch_id: batch-cb3c
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-26 15:14:09.583597+00:00
last_modified: 2023-09-26 15:14:09.583603+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG3408
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG3408
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྤྱོད་འཇུག་གི་རྣམ་པར་བཤད་པ་སོགས་འགྲེལ་པ་ཁག་ཅིག
  languages:
  - bo
  author: ལོ་ཆེན་བཻ་རོ་ཙ་ན།
statistics:
  ocr_word_mean_confidence_index: 0.9971066705568308
  ocr_word_median_confidence_index: 0.9999999
bases:
  I1KG3497:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3497
      total_pages: 1736
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3497.txt
    statistics:
      ocr_word_median_confidence_index: 0.9999999
      ocr_word_mean_confidence_index: 0.9971066705568308
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
